# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [1]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [21]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.8024685  0.08568437 0.47863696 ... 0.84675664 0.1842706  0.45360153]
 [0.72086844 0.02112049 0.21318737 ... 0.9286165  0.76041377 0.72245714]
 [0.70812986 0.19527099 0.09960543 ... 0.36604853 0.71836608 0.18100416]
 ...
 [0.70836861 0.93528334 0.68441446 ... 0.13523968 0.0842791  0.31005473]
 [0.0177566  0.32029584 0.96182992 ... 0.8407581  0.99009708 0.58295957]
 [0.12292269 0.51734454 0.34842855 ... 0.47983109 0.87330051 0.71578686]]
[[0.00981694 0.9083377  0.90775699 ... 0.66791773 0.19775401 0.38991904]
 [0.88435041 0.31452031 0.64669165 ... 0.38607674 0.04045445 0.83621919]
 [0.91688365 0.64083145 0.66428892 ... 0.48815828 0.98018269 0.01378794]
 ...
 [0.01526347 0.40794341 0.63669921 ... 0.05563893 0.86722723 0.05941196]
 [0.9721679  0.34403379 0.5464532  ... 0.13327585 0.6748931  0.32627401]
 [0.26273184 0.66436795 0.03316377 ... 0.94296183 0.08255643 0.73482993]]


Без использования numpy

In [22]:
def mult(a, b):
    result = []
    for i in range(len(a)):
        row = []
        for j in range(len(b[0])):
            value = sum(a[i][k] * b[k][j] for k in range(len(b)))
            row.append(value)
        result.append(row)
    return result

C использованием numpy

In [23]:
def np_mult(a, b):
    result = np.dot(a, b)
    return result

In [24]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 684 ms, sys: 1.3 ms, total: 685 ms
Wall time: 692 ms


In [25]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 1.56 ms, sys: 4.1 ms, total: 5.66 ms
Wall time: 5.43 ms


In [26]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.4718892771270475e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [27]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.33848045 0.78161768 0.79467356] [0.27277122 0.77283239 0.68614495]


In [28]:
def scalar_product(a,b):
    s = 0
    for i in range(len(a)):
        s += a[i] * b[i]
    return s

In [29]:
def np_scalar_product(a,b):
    s = np.dot(a, b)
    return s

In [30]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 20 µs, sys: 3 µs, total: 23 µs
Wall time: 26.9 µs
CPU times: user 512 µs, sys: 9 µs, total: 521 µs
Wall time: 488 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** NumPy предоставляет эффективные методы для работы с массивами и матрицами благодаря своей оптимизированной реализации на языке C.

------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [79]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  try:
    if len(a) > 0 and len(a[0]) == len(a):
      diagonal_elements = np.diag(a)[::2]
      res = np.sum(diagonal_elements)
      return res
    else:
      return 0
  except IndexError:
      return 1

In [80]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[5, 9, 7, 4, 6]])

In [81]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 17 µs, sys: 2 µs, total: 19 µs
Wall time: 23.4 µs


0

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [90]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(*A):
    result = np.cumsum(np.array(A), axis=1) / np.arange(1, np.array(A).shape[1] + 1)
    return result

In [93]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)
print(np_sec_av(A))

[0.84846643 0.66733721 0.12275841 0.46564594 0.10481834 0.96253652
 0.22667202 0.99407211 0.96932864 0.22141324 0.26086006 0.44723133
 0.54204024 0.08324262 0.14151767 0.13579809 0.11155541 0.65604736
 0.97858288 0.57158416 0.40602255 0.31971388 0.16696908 0.03164991
 0.11681113 0.68074201 0.45784712 0.87084671 0.25822358 0.63647425
 0.45860284 0.75883513 0.5184532  0.70894141 0.86232166 0.89007894
 0.26360761 0.58946496 0.98604062 0.6590837  0.39642984 0.81869306
 0.83940621 0.75928015 0.68245453 0.26827229 0.71290921 0.11080088
 0.18293976 0.58764322 0.9767596  0.58568386 0.52611687 0.08329434
 0.91673325 0.65966028 0.47170119 0.46385521 0.11401749 0.38222867
 0.46553381 0.13641149 0.33164004 0.70213332 0.69736191 0.61592491
 0.70569841 0.44953751 0.04054483 0.59692583 0.13988305 0.81283378
 0.72503708 0.05436144 0.07088652 0.8358599  0.35534575 0.36370467
 0.93389982 0.57966144 0.29518018 0.61136911 0.48301745 0.7123151
 0.58174936 0.61632412 0.39911645 0.71260703 0.46330773 0.79786

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [103]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    if len(a) == 0:
        return np.array([]), np.array([])
    current_element = a[0]
    count = 1
    encoded_elements = []
    repetitions = []
    for element in a[1:]:
        if element == current_element:
            count += 1
        else:
            encoded_elements.append(current_element)
            repetitions.append(count)

            current_element = element
            count = 1

    # Добавляем последний элемент и его счетчик
    encoded_elements.append(current_element)
    repetitions.append(count)

    return np.array(encoded_elements), np.array(repetitions)

In [104]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)
print(np_encode(X))

CPU times: user 34 µs, sys: 4 µs, total: 38 µs
Wall time: 42 µs
(array([1, 2, 3, 1, 5, 2, 3]), array([1, 2, 2, 2, 2, 1, 2]))


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [105]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    transformed_X = X.copy()

    transformed_X[1::2] = a
    transformed_X[::2] = transformed_X[::2] ** 3

    reversed_X = transformed_X[::-1]

    result = np.concatenate((X, reversed_X))

    return result

In [108]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)
print(X)
print(np_transformation(X, 5))

CPU times: user 1.2 ms, sys: 0 ns, total: 1.2 ms
Wall time: 1.29 ms
[1 3 5 7 9]
[  1   3   5   7   9 729   5 125   5   1]
